import { ThemeColor } from '@/contexts/ThemeContext';

export function getThemeColors(theme: ThemeColor) {
  const colors = {
    red: {
      gradient: 'from-red-600 to-red-800',
      gradientReverse: 'from-red-800 to-red-600',
      gradientAlt: 'from-red-500 to-orange-600',
      gradientText: 'bg-gradient-to-r from-red-400 to-red-600 bg-clip-text text-transparent',
      bg: 'bg-red-600',
      bgLight: 'bg-red-600/20',
      bgButton: 'bg-red-600',
      bgButtonHover: 'hover:bg-red-700',
      bgButtonHoverInner: 'bg-red-700',
      bgHover: 'hover:bg-red-600/10',
      bgActive: 'bg-red-600/20',
      text: 'text-red-400',
      textBold: 'bg-gradient-to-r from-red-400 to-red-600 bg-clip-text text-transparent',
      textStats: 'text-red-400',
      textHover: 'hover:text-red-400',
      textBadge: 'text-red-400',
      border: 'border-red-600',
      borderLight: 'border-red-600/30',
      borderButton: 'border-red-600',
      borderButtonHover: 'hover:border-red-700',
      borderHover: 'hover:border-red-600',
      borderBadge: 'border-red-600',
      badge: 'bg-red-600/20',
      frameBorder: 'border-red-600',
      frameBorderLight: 'border-red-600/30',
      accentLine: 'from-red-600 via-red-500 to-red-600',
      scrollIndicator: 'text-red-400',
      decorative: 'bg-red-600/20',
      decorativeBorder: 'border-red-600/30',
    },
    blue: {
      gradient: 'from-blue-600 to-blue-800',
      gradientReverse: 'from-blue-800 to-blue-600',
      gradientAlt: 'from-blue-500 to-cyan-600',
      gradientText: 'bg-gradient-to-r from-blue-400 to-blue-600 bg-clip-text text-transparent',
      bg: 'bg-blue-600',
      bgLight: 'bg-blue-600/20',
      bgButton: 'bg-blue-600',
      bgButtonHover: 'hover:bg-blue-700',
      bgButtonHoverInner: 'bg-blue-700',
      bgHover: 'hover:bg-blue-600/10',
      bgActive: 'bg-blue-600/20',
      text: 'text-blue-400',
      textBold: 'bg-gradient-to-r from-blue-400 to-blue-600 bg-clip-text text-transparent',
      textStats: 'text-blue-400',
      textHover: 'hover:text-blue-400',
      textBadge: 'text-blue-400',
      border: 'border-blue-600',
      borderLight: 'border-blue-600/30',
      borderButton: 'border-blue-600',
      borderButtonHover: 'hover:border-blue-700',
      borderHover: 'hover:border-blue-600',
      borderBadge: 'border-blue-600',
      badge: 'bg-blue-600/20',
      frameBorder: 'border-blue-600',
      frameBorderLight: 'border-blue-600/30',
      accentLine: 'from-blue-600 via-blue-500 to-blue-600',
      scrollIndicator: 'text-blue-400',
      decorative: 'bg-blue-600/20',
      decorativeBorder: 'border-blue-600/30',
    },
    green: {
      gradient: 'from-green-600 to-green-800',
      gradientReverse: 'from-green-800 to-green-600',
      gradientAlt: 'from-green-500 to-emerald-600',
      gradientText: 'bg-gradient-to-r from-green-400 to-green-600 bg-clip-text text-transparent',
      bg: 'bg-green-600',
      bgLight: 'bg-green-600/20',
      bgButton: 'bg-green-600',
      bgButtonHover: 'hover:bg-green-700',
      bgButtonHoverInner: 'bg-green-700',
      bgHover: 'hover:bg-green-600/10',
      bgActive: 'bg-green-600/20',
      text: 'text-green-400',
      textBold: 'bg-gradient-to-r from-green-400 to-green-600 bg-clip-text text-transparent',
      textStats: 'text-green-400',
      textHover: 'hover:text-green-400',
      textBadge: 'text-green-400',
      border: 'border-green-600',
      borderLight: 'border-green-600/30',
      borderButton: 'border-green-600',
      borderButtonHover: 'hover:border-green-700',
      borderHover: 'hover:border-green-600',
      borderBadge: 'border-green-600',
      badge: 'bg-green-600/20',
      frameBorder: 'border-green-600',
      frameBorderLight: 'border-green-600/30',
      accentLine: 'from-green-600 via-green-500 to-green-600',
      scrollIndicator: 'text-green-400',
      decorative: 'bg-green-600/20',
      decorativeBorder: 'border-green-600/30',
    },
  };

  return colors[theme];
}

